### ISSUE TITLE
Python error when getting status on removed project

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-mergin-plugin#263]
1) Download a project using the plugin
2) Delete the project manually (not using plugin)
3) Plugin still thinks projects is downloaded. Check the status of project and it fails

2021-06-14T10:27:26     WARNING    Traceback (most recent call last):
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 444, in project_status
              self.project_manager.project_status(self.path)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/projects_manager.py", line 147, in project_status
              mp = MerginProject(project_dir)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/merginproject.py", line 39, in __init__
              raise InvalidProject('Project directory does not exist')
             Mergin.mergin.common.InvalidProject: Project directory does not exist

**Comment by jozef-budac** [comment]
Verified
