### ISSUE TITLE
Download freeze at 85%

### ISSUE THREAD

**Issue by snedchuck** [MerginMaps/qgis-mergin-plugin#339]
Attempting to download projects from Mergin but downloads take unusually long time to complete or freeze between 50% and 85%. Failure message upon download completion. 

Details from error msg:
```
Traceback (most recent call last):

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 138, in download_timer_tick
    download_project_finalize(self.job)

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 207, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 256, in apply
    file_to_merge.merge()

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 500, in merge
    raise ClientError('Download of file {} failed. Please try it again.'.format(self.dest_file))

Mergin.mergin.common.ClientError: Download of file C:\NetPMD\MerginProjects\Rockford Network\Trench.gpkg failed. Please try it again.
```
![Screenshot 2022-02-10 131000](https://user-images.githubusercontent.com/99442033/153497030-acbe347a-da5b-4857-b4ac-cdb58cb74435.png)

**Comment by snedchuck** [comment]
Changed Mergin accounts, full remove and install of QGIS 3.16.16, changed destination folder, same result.

Traceback (most recent call last):

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 138, in download_timer_tick
    download_project_finalize(self.job)

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 207, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 256, in apply
    file_to_merge.merge()

  File "C:\Users/Charles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 500, in merge
    raise ClientError('Download of file {} failed. Please try it again.'.format(self.dest_file))

Mergin.mergin.common.ClientError: Download of file C:\NetPMD\TestFolder\Rockford Network\Trench.gpkg failed. Please try it again.

**Comment by PeterPetrik** [comment]
@snedchuck we have done some major refactoring of the server and plugin code to improve sync. Can you update to latest version and try again?
