### ISSUE TITLE
Validation problem stops the project to sync

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#438]
A user gets the following error and cannot sync his project:
```

2022-07-07T17:57:09     WARNING    Traceback (most recent call last):
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 308, in current_project_sync
              self.manager.project_status(self.mergin_proj_dir)
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\projects_manager.py", line 163, in project_status
              validation_results = validator.run_checks()
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 87, in run_checks
              self.check_attachment_widget()
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 196, in check_attachment_widget
              if cfg["RelativeStorage"] == 0:
             KeyError: 'RelativeStorage'
```

**Comment by ldebek** [comment]
Sample data is needed to reproduce this issue.
