### ISSUE TITLE
Error after update 2022.5

### ISSUE THREAD

**Issue by bellanz80** [MerginMaps/qgis-mergin-plugin#440]
Hi.
I had Mergin (qgis plug) version 2022.4.1 installed, both in QGIS 3.22 and 3.26, in windows 10. No problem.

But, after updating the mergin qgis plug to version 2022.5, I had errors when opening the project properties panel, where the GUI becomes unstable and the texts overlap, making it unusable.
In fact, the very update of the plug, to version 2022.5, ends with errors, but apparently then it lets you use the mergin and connect to the online account.

I tried a new, clean profile and no more problems, but I can't just use a new profile as the old one worked perfectly with all my settings.

If I go to the plug panel, and deactivate Mergin, the project properties panel works perfectly again.

![image](https://user-images.githubusercontent.com/38449926/178316842-3c824fd8-14e0-42f7-916b-4fd7419aaa63.png)
![image](https://user-images.githubusercontent.com/38449926/178316886-1c85f848-58ee-4ffa-a99a-76dc4f81a4a6.png)
![image](https://user-images.githubusercontent.com/38449926/178316929-08ebd59b-9188-4e43-b8f3-b03abe35d5b4.png)

https://user-images.githubusercontent.com/38449926/178317492-087c9dab-5e7e-4c6f-a76c-afb5415928e3.mp4

SO: windows 10
QGIS: 3.26 / 3.22 (osgeo)

**Comment by roya0045** [comment]
Confirmed on my end too, causing crash whenever I open the project setting dialogs in master build, and cause a display error in 3.24 
![image](https://user-images.githubusercontent.com/12854129/178734346-d4e128cd-fcf5-4ca5-8a69-1af47df209bc.png)

**Comment by ldebek** [comment]
@bellanz80 Could you please attach a Python Error message which you are getting when this issue occurs?

**Comment by roya0045** [comment]
> @bellanz80 Could you please attach a Python Error message which you are getting when this issue occurs?

I got the following on 3.24 when opening the project properties dialog.

>   File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\project_settings_widget.py", line 42, in __init__
    self.cmb_snapping_mode.addItem("No snapping", 0)
AttributeError: 'ProjectConfigWidget' object has no attribute 'cmb_snapping_mode'

And the Mergin tab in the properties dialog doesn't 'contain' anything, the button doesn't seem to trigger a change in the UI.

**Comment by roya0045** [comment]
@ldebek Tried to reinstall the plugin got an error. Somehow the changes in the python file occur, but the changes in the ui files are not there. If I try/except the code related to snapping in the confing class, it works fine.

**Comment by bellanz80** [comment]
> 

2022-07-26T22:37:36     WARNING    Traceback (most recent call last):
              File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\Mergin\project_settings_widget.py", line 25, in createWidget
              return ProjectConfigWidget(parent)
              File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\Mergin\project_settings_widget.py", line 42, in __init__
              self.cmb_snapping_mode.addItem("No snapping", 0)
             AttributeError: 'ProjectConfigWidget' object has no attribute 'cmb_snapping_mode'
