### ISSUE TITLE
Failure to sync project due to an unhandled exception

### ISSUE THREAD

**Issue by DaleMaskeAM** [MerginMaps/qgis-mergin-plugin#465]
"This should not happen, please report the problem" - brought me here.

I tried to sync one of our workpackages 'agmc/CFA_BoRadyn' and recieved the error that I have pasted below.

> Traceback (most recent call last):

  File "C:\Users/Dale/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 222, in push_timer_tick
    push_project_finalize(self.job)

  File "C:\Users/Dale/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 267, in push_project_finalize
    server_resp_cancel = json.load(resp_cancel)

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tomasMizera** [comment]
Thank you for the report, the issue with "unhandled exception" is now fixed. Please reach out to our support at [support@merginmaps.com](mailto:support@merginmaps.com) if you still have issues.
