### ISSUE TITLE
App crash during sync with temporary layer

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-mergin-plugin#476]
Scenario:
1) open any kind of vector layer project
2) use tool 'Import geotagged photos -> new temporary layer will be created
3) hit sync -> the plugin crashes

```
An error has occurred while executing Python code: 

KeyError: 'RelativeStorage' 
Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/plugin.py", line 309, in current_project_sync
    self.manager.project_status(self.mergin_proj_dir)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/projects_manager.py", line 167, in project_status
    dlg = ProjectStatusDialog(
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/project_status_dialog.py", line 85, in __init__
    self.validate_project()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/project_status_dialog.py", line 224, in validate_project
    results = validator.run_checks()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/validation.py", line 99, in run_checks
    self.check_attachment_widget()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/validation.py", line 210, in check_attachment_widget
    if cfg["RelativeStorage"] == 0:
KeyError: 'RelativeStorage'


Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] 
QGIS version: 3.22.13-Białowieża Białowieża, 02ff117c4e 

Python Path:
/usr/share/qgis/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/jozef/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python
.
/home/jozef/Lutra/projects/tc04_recording_6

**Comment by wonder-sk** [comment]
Duplicate of #459 ?

**Comment by wonder-sk** [comment]
(a fix is now on the master branch - can you try again?)

**Comment by jozef-budac** [comment]
Yes, it fixed on master
