### ISSUE TITLE
Sync Problem

### ISSUE THREAD

**Issue by grantboxer** [MerginMaps/qgis-mergin-plugin#498]
When I sync from my table to the server, then try to sync with my PC, I get the following message.
Traceback (most recent call last):

  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 284, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 626, in pull_project_finalize
    shutil.rmtree(job.temp_dir)

  File "C:\OSGeo4W\apps\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\OSGeo4W\apps\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\OSGeo4W\apps\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\Dropbox\\AusQuest\\Balladonia\\GB_FieldData1\\.mergin\\fetch_v9-v10\\Balla_Drill_Data.gpkg-server_diff'

**Comment by alexbruy** [comment]
Duplicates #276.

Citing @wonder-sk 

>  it is not a good idea to have Mergin projects stored within Dropbox folder, because the sync from Dropbox interferes with the sync in Mergin, causing problems like you got. Or try pausing Dropbox sync while you sync data with Mergin
